
# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           /:title
relative_permalinks: true

# Setup
timezone:            your timezone # eg. Asia/Kathmandu
locale:              en_us # eg. en_us
name:				         Kurt Mansperger
title:               Kurt Mansperger
tagline:             Helping to improve inefficiencies
description:         Life is about enjoying new challenges and learning along the way. These articles attempt to share what I have learned in an effort to make others lives more enjoyable. 
url:                 kurtmansperger.com
rss:                 feed.xml
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                '/assets/img/icon.png'
disqus:              kurtmansperger

author:
  name:           	 Kurt Mansperger
  url:            	 kurtmansperger.com
  facebook:          kurtmansperger
  linkedin:          kurtmansperger

fb_admins:           kurtmansperger
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
